import "../public/assets/css/ai-solutions-css/vendors/bootstrap.min.css";
import "../public/assets/css/ai-solutions-css/vendors/swiper-bundle.min.css";
import "../public/assets/css/ai-solutions-css/vendors/aos.css";
import "../public/assets/css/ai-solutions-css/vendors/carouselTicker.css";
import "../public/assets/css/ai-solutions-css/vendors/odometer.css";
import "../public/assets/css/ai-solutions-css/vendors/magnific-popup.css";
import "../public/assets/fonts/ai-solutions-fonts/bootstrap-icons/bootstrap-icons.min.css";
import "../public/assets/fonts/ai-solutions-fonts/boxicons/boxicons.min.css";
import "../public/assets/fonts/ai-solutions-fonts/remixicon/remixicon.css";
import "../public/assets/fonts/ai-solutions-fonts/fontawesome/fontawesome.min.css";
import "../public/assets/fonts/ai-solutions-fonts/fontawesome/solid.min.css";
import "../public/assets/fonts/ai-solutions-fonts/fontawesome/regular.min.css";
import "../public/assets/css/ai-solutions-css/main.css";

import "../public/assets/css/ai-solutions-css/style.css";

import type { Metadata } from "next";
import { Libre_Franklin, Rubik } from "next/font/google";

const LibreFranklinHeading = Libre_Franklin({
    weight: ["300", "400", "500", "600", "700"], // Only bold for headings
    subsets: ["latin"],
    variable: "--tc-heading-font-family",
    display: "swap",
});

const rubik = Rubik({
    weight: ["300", "400", "500", "600", "700"],
    subsets: ["latin"],
    variable: "--tc-body-font-family",
    display: "swap",
});

export const metadata: Metadata = {
    title: "xzectlabs",
    description: "Generated by Astra-X - Multi-purpose Bootstrap 5 Next.js Template",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${LibreFranklinHeading.variable} ${rubik.variable}`} style={{ backgroundColor: '#ffffff' }}>{children}</body>
        </html>
    );
}
